# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import functions_pb2 as functions__pb2


class FederatedAppStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitializeParams = channel.unary_unary(
                '/FederatedApp/InitializeParams',
                request_serializer=functions__pb2.InitialParams.SerializeToString,
                response_deserializer=functions__pb2.Empty.FromString,
                )
        self.GenerateData = channel.unary_unary(
                '/FederatedApp/GenerateData',
                request_serializer=functions__pb2.Empty.SerializeToString,
                response_deserializer=functions__pb2.Empty.FromString,
                )
        self.Train = channel.unary_unary(
                '/FederatedApp/Train',
                request_serializer=functions__pb2.Empty.SerializeToString,
                response_deserializer=functions__pb2.Model.FromString,
                )
        self.SendModel = channel.unary_unary(
                '/FederatedApp/SendModel',
                request_serializer=functions__pb2.Model.SerializeToString,
                response_deserializer=functions__pb2.Empty.FromString,
                )


class FederatedAppServicer(object):
    """Missing associated documentation comment in .proto file"""

    def InitializeParams(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateData(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Train(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendModel(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederatedAppServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitializeParams': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeParams,
                    request_deserializer=functions__pb2.InitialParams.FromString,
                    response_serializer=functions__pb2.Empty.SerializeToString,
            ),
            'GenerateData': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateData,
                    request_deserializer=functions__pb2.Empty.FromString,
                    response_serializer=functions__pb2.Empty.SerializeToString,
            ),
            'Train': grpc.unary_unary_rpc_method_handler(
                    servicer.Train,
                    request_deserializer=functions__pb2.Empty.FromString,
                    response_serializer=functions__pb2.Model.SerializeToString,
            ),
            'SendModel': grpc.unary_unary_rpc_method_handler(
                    servicer.SendModel,
                    request_deserializer=functions__pb2.Model.FromString,
                    response_serializer=functions__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FederatedApp', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FederatedApp(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def InitializeParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FederatedApp/InitializeParams',
            functions__pb2.InitialParams.SerializeToString,
            functions__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FederatedApp/GenerateData',
            functions__pb2.Empty.SerializeToString,
            functions__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Train(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FederatedApp/Train',
            functions__pb2.Empty.SerializeToString,
            functions__pb2.Model.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FederatedApp/SendModel',
            functions__pb2.Model.SerializeToString,
            functions__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
