version: "3"
services:
  node01:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "5081:8080"
    volumes:
      - /data/node01:/app/data

  node02:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "5082:8080"
    volumes:
      - /data/node02:/app/data

  node03:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "5083:8080"
    volumes:
      - /data/node03:/app/data

  node04:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "5084:8080"
    volumes:
      - /data/node04:/app/data

  node05:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "5085:8080"
    volumes:
      - /data/node05:/app/data