# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='node.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\nnode.proto\"\x16\n\x05Model\x12\r\n\x05model\x18\x01 \x01(\t\"\x16\n\x05\x45mpty\x12\r\n\x05value\x18\x01 \x01(\x05\"\x1c\n\x0bPredictions\x12\r\n\x05value\x18\x01 \x01(\x05\"\xb4\x01\n\x10InitializeParams\x12\r\n\x05\x61lpha\x18\x01 \x01(\x01\x12\r\n\x05index\x18\x02 \x01(\x01\x12\x0c\n\x04isDC\x18\x03 \x01(\x01\x12\x10\n\x08\x64\x63_index\x18\x04 \x01(\x05\x12\x14\n\x0c\x64\x65vice_index\x18\x05 \x01(\x05\x12\x19\n\x11\x63oordinate_per_dc\x18\x06 \x01(\x05\x12\x1d\n\x15\x64\x61tapoints_per_device\x18\x07 \x01(\x05\x12\x12\n\nrandomseed\x18\x08 \x01(\x05\"#\n\x0bTrainParams\x12\x14\n\x0clocal_epochs\x18\x01 \x01(\x05\"\x1e\n\x0cUpdateParams\x12\x0e\n\x06params\x18\x01 \x01(\t2\xd1\x01\n\rFederatedNode\x12-\n\x0eInitializeData\x12\x11.InitializeParams\x1a\x06.Empty\"\x00\x12\x1f\n\x05Train\x12\x0c.TrainParams\x1a\x06.Model\"\x00\x12&\n\x0bUpdateState\x12\r.UpdateParams\x1a\x06.Empty\"\x00\x12\x1d\n\tSendModel\x12\x06.Model\x1a\x06.Empty\"\x00\x12)\n\x0fSendPredictions\x12\x06.Empty\x1a\x0c.Predictions\"\x00\x62\x06proto3'
)




_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='Model.model', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=36,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Empty.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=60,
)


_PREDICTIONS = _descriptor.Descriptor(
  name='Predictions',
  full_name='Predictions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Predictions.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=90,
)


_INITIALIZEPARAMS = _descriptor.Descriptor(
  name='InitializeParams',
  full_name='InitializeParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='alpha', full_name='InitializeParams.alpha', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='InitializeParams.index', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isDC', full_name='InitializeParams.isDC', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dc_index', full_name='InitializeParams.dc_index', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_index', full_name='InitializeParams.device_index', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coordinate_per_dc', full_name='InitializeParams.coordinate_per_dc', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='datapoints_per_device', full_name='InitializeParams.datapoints_per_device', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='randomseed', full_name='InitializeParams.randomseed', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=273,
)


_TRAINPARAMS = _descriptor.Descriptor(
  name='TrainParams',
  full_name='TrainParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='local_epochs', full_name='TrainParams.local_epochs', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=310,
)


_UPDATEPARAMS = _descriptor.Descriptor(
  name='UpdateParams',
  full_name='UpdateParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='params', full_name='UpdateParams.params', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=342,
)

DESCRIPTOR.message_types_by_name['Model'] = _MODEL
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Predictions'] = _PREDICTIONS
DESCRIPTOR.message_types_by_name['InitializeParams'] = _INITIALIZEPARAMS
DESCRIPTOR.message_types_by_name['TrainParams'] = _TRAINPARAMS
DESCRIPTOR.message_types_by_name['UpdateParams'] = _UPDATEPARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), {
  'DESCRIPTOR' : _MODEL,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:Model)
  })
_sym_db.RegisterMessage(Model)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

Predictions = _reflection.GeneratedProtocolMessageType('Predictions', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTIONS,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:Predictions)
  })
_sym_db.RegisterMessage(Predictions)

InitializeParams = _reflection.GeneratedProtocolMessageType('InitializeParams', (_message.Message,), {
  'DESCRIPTOR' : _INITIALIZEPARAMS,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:InitializeParams)
  })
_sym_db.RegisterMessage(InitializeParams)

TrainParams = _reflection.GeneratedProtocolMessageType('TrainParams', (_message.Message,), {
  'DESCRIPTOR' : _TRAINPARAMS,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:TrainParams)
  })
_sym_db.RegisterMessage(TrainParams)

UpdateParams = _reflection.GeneratedProtocolMessageType('UpdateParams', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEPARAMS,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:UpdateParams)
  })
_sym_db.RegisterMessage(UpdateParams)



_FEDERATEDNODE = _descriptor.ServiceDescriptor(
  name='FederatedNode',
  full_name='FederatedNode',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=345,
  serialized_end=554,
  methods=[
  _descriptor.MethodDescriptor(
    name='InitializeData',
    full_name='FederatedNode.InitializeData',
    index=0,
    containing_service=None,
    input_type=_INITIALIZEPARAMS,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Train',
    full_name='FederatedNode.Train',
    index=1,
    containing_service=None,
    input_type=_TRAINPARAMS,
    output_type=_MODEL,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateState',
    full_name='FederatedNode.UpdateState',
    index=2,
    containing_service=None,
    input_type=_UPDATEPARAMS,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendModel',
    full_name='FederatedNode.SendModel',
    index=3,
    containing_service=None,
    input_type=_MODEL,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendPredictions',
    full_name='FederatedNode.SendPredictions',
    index=4,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_PREDICTIONS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FEDERATEDNODE)

DESCRIPTOR.services_by_name['FederatedNode'] = _FEDERATEDNODE

# @@protoc_insertion_point(module_scope)
